title: DLS Practice (Sandbox)
email: wes_peacock@sil.org
remote_theme: just-the-docs/just-the-docs
# color_scheme: "dark"
search_enabled: true
exclude: ["stagefiles"]

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# required for building jekyll site locally
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
