
title: DLS Practice (Sandbox)
email: wes_peacock@sil.org
description:
 - This site collects details about all aspects of importing an SFM database into FLEx.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# theme: minima
theme: just-the-docs

plugins:
  - jekyll-feed

exclude: ["stagefiles"]
